# Use a minimal base image
FROM python:3.9-slim

# Update and upgrade system packages
RUN apt-get update && apt-get upgrade -y && apt-get install -y --no-install-recommends \
    build-essential \
    && rm -rf /var/lib/apt/lists/* && pip install --upgrade pip

# Create a non-root user
RUN groupadd -r sruser && useradd -r -g sruser sruser

# Set the working directory
WORKDIR /app

# Copy only necessary files
COPY requirements.txt /app/
RUN pip install --no-cache-dir -r requirements.txt

COPY . /app

# Switch to the non-root user
USER sruser

CMD ["python", "app.py"]